system-ghc: false

#resolver: lts-11.22

# ghc 8.4.3
resolver: lts-12.11

# ghc 8.6.1
#resolver: nightly-2018-10-03

# Local packages, usually specified by relative directory name
packages:
- '.'
# - ../flat

flags:
   serialise:
     newtime15: true

extra-deps:
- flat-0.3.2
- packman-0.5.0
# - binary-0.8.5.1
- cereal-0.5.7.0
- store-0.5.0
- serialise-0.2.0.0
- datasets-0.2.1
