system-ghc: false

resolver: nightly-2022-02-07

# Local packages, usually specified by relative directory name
packages:
- '.'
# - ../flat

flags:
   serialise:
     newtime15: true

# extra-deps:
# - packman-0.5.0@sha256:ea773d5f197f3b4c54d97e208de9bbf217e39af28eced7b863697f621521be38,6887
