system-ghc: false

# ghc 8.4.4
resolver: lts-12.16

# ghc 8.6.1
#resolver: nightly-2018-10-03

# Local packages, usually specified by relative directory name
packages:
- '.'
# - ../flat

flags:
   serialise:
     newtime15: true

extra-deps:
- flat-0.3.2
- persist-0.1
- packman-0.5.0
# - binary-0.8.5.1
- cereal-0.5.7.0
- store-0.5.0.1
- serialise-0.2.1.0
- datasets-0.2.1
